
[id='tracing-complex-service_{context}']
= Tracing a complex service

In the second example, we'll show how to trace a more complex service that performs an external invocation.
To keep the example easy to use, the application will actually call itself, but in a way that is indistinguishable from calling actual services outside of the application.

.Prerequisites

* You have completed the previous example.
You might want to restart the Jaeger tracer.

.Procedure

. Use JAX-RS Client to invoke an external service.
+
--
.MyComplexResource.java
[source,java]
----
include::src/main/java/org/wildfly/swarm/howto/tracing/MyComplexResource.java[tag=complex-resource,indent=0]
----

.MyService.java
[source,java]
----
include::src/main/java/org/wildfly/swarm/howto/tracing/MyService.java[tag=traced-service-method,indent=0]
----

Here, we show that not only JAX-RS resource methods can be traced.
This is a regular method in a CDI bean.
Unlike JAX-RS resources, which are traced automatically, other methods need an explicit `@Traced` annotation.

The most important part is this usage of MicroProfile OpenTracing API:

[source,java]
----
include::src/main/java/org/wildfly/swarm/howto/tracing/MyService.java[tag=client-registration,indent=0]
----

This is how MicroProfile OpenTracing integrates with JAX-RS Client to make sure the trace is propagated across services.
Without this, it would be impossible to correlate the invocations as part of a single user request.

Currently, MicroProfile OpenTracing doesn't integrate with MicroProfile RestClient, so you need to use a pure JAX-RS Client.
This limitation will be lifted in the future, see link:https://github.com/eclipse/microprofile-opentracing/issues/82[issue #82].
--

. Invoke the traced endpoint several times.
+
--
[source,bash]
----
$ curl http://localhost:8080/complex
Called an external service successfully, it responded: Hello from traced endpoint
----

Notice how the "complex" service calls the "simple" service, which we've seen in the previous example.
Both of these services are traced, so we will see the invocation of "simple" as a part of the "complex" invocation.
--

. See the traces in Jaeger UI.
+
--
Reload the Jaeger UI at link:http://localhost:16686/[http://localhost:16686/], select `greeter` under _Service_ and click _Find Traces_.
You will see all the requests you performed and some basic information about them.

Click on one of the traces to show detailed information about that particular request.
At the top level, you see the JAX-RS resource method `MyComplexResource.get`.
Under it, you see the invocation of `MyService.call` method.
Under that, you see that this method performed a `GET` request to another service.
And finally, under that `GET` request, you see the JAX-RS resource method `MySimpleResource.get`.
For all these invocations, you see how long they took and when did they occur as part of the entire request processing.
--
