
[id='what-is-distributed-tracing_{context}']
= What is distributed tracing

In microservices architecture, where multiple services are invoked in order to serve a single user request, debugging might be particularly hard.
One of the techniques that are often employed to make it easier is called _distributed tracing_.
Distributed tracing means collecting information about service invocations, correlating them to find all invocations pertaining to a single user request, and visualizing them in a form that helps understanding the hierarchy of invocations and finding problems.

{Thorntail} provides a fraction for link:https://github.com/eclipse/microprofile-opentracing[MicroProfile OpenTracing], an easy to use API for distributed tracing, built on top of JAX-RS and link:http://opentracing.io/[OpenTracing].
Another fraction is provided to configure link:https://www.jaegertracing.io/[Jaeger], one of the popular tracers.
Together, these two fractions are all that's required on the application side.
Outside of the application, it is expected that a tracer will be running in the environment.
In this example, we'll run Jaeger locally, using Docker.
