
package org.wildfly.swarm.webservices;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "echoService", targetNamespace = "webservices.swarm.wildfly.org", wsdlLocation = "http://localhost:8080/ws/echo?wsdl")
@HandlerChain(file = "/org/wildfly/swarm/webservices/handler-chain.xml")
public class EchoServiceClientWithHandler
    extends Service
{

    private final static URL ECHOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECHOSERVICE_EXCEPTION;
    private final static QName ECHOSERVICE_QNAME = new QName("webservices.swarm.wildfly.org", "echoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/echo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOSERVICE_WSDL_LOCATION = url;
        ECHOSERVICE_EXCEPTION = e;
    }

    public EchoServiceClientWithHandler() {
        super(__getWsdlLocation(), ECHOSERVICE_QNAME);
    }

    public EchoServiceClientWithHandler(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOSERVICE_QNAME, features);
    }

    public EchoServiceClientWithHandler(URL wsdlLocation) {
        super(wsdlLocation, ECHOSERVICE_QNAME);
    }

    public EchoServiceClientWithHandler(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOSERVICE_QNAME, features);
    }

    public EchoServiceClientWithHandler(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoServiceClientWithHandler(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "echoPort")
    public EchoService getEchoPort() {
        return super.getPort(new QName("webservices.swarm.wildfly.org", "echoPort"), EchoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "echoPort")
    public EchoService getEchoPort(WebServiceFeature... features) {
        return super.getPort(new QName("webservices.swarm.wildfly.org", "echoPort"), EchoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOSERVICE_EXCEPTION!= null) {
            throw ECHOSERVICE_EXCEPTION;
        }
        return ECHOSERVICE_WSDL_LOCATION;
    }

}
