[#component-datasources]
= DataSources

The DataSources component provides access to managed JDBC datasources.

.Maven Coordinates

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>{groupId}</groupId>
  <artifactId>{project_key}-datasources</artifactId>
</dependency>
----

.Configuration

DataSources may be configured by providing a set of configuration properties for each datasource.
Each configuration property has the prefix of `datasource._MyDS_`.

`datasource._MyDS_.username`::
The username for connecting to the datasource.

`datasource._MyDS_.password`::
The password for connecting to the datasource.

`datasource._MyDS_.connection-url`::
The JDBC connection URL for the datasource.

`datasource._MyDS_.driver`::
The simple identifier of the JDBC driver for the datasource.

`datasource._MyDS_.trace`::
Enable tracing if `OpenTracing` is available. Acceptable values are `OFF`, `ALWAYS`, and `ACTIVE`. 
By setting to `ACTIVE`, only usage of the datasource when there is already an active parent context will be traced. 

.Related Information

* xref:component-jdbc[]
* xref:component-jca[]
