[#component-jms]
= JMS

The JMS component provides for easily connecting to remote message brokers.

.Maven Coordinates

[source,xml]
----
<dependency>
  <groupId>org.jboss.unimbus</groupId>
  <artifactId>jms</artifactId>
</dependency>
----

.Configuration

By default, ActiveMQ-Artemis client is provided, and respects the following configuration options:

`artemis.username`::
The username for the remote connection>

`artemis.password`::
The password for the remote connection.

`artemis.url`::
The remote connection URL, which must be set unless less `artemis.host` and `artemis.port` are used.

`artemis.host`::
The remote connection host, if not using `artemis.url`. Defaults to `localhost`.

`artemis.port`::
The remote connection port, if not using `artemis.url`. Defaults to `61616`.

== Resource Adapter

If the Artemis resource adapter artifact is found as a dependency of the project, it will automatically be deployed.
The resource adapter will be configured using the same connection and authentication information as the normal Artemis JMS client.

== CDI Components

`JMSContext`::
Injectable JMS context which may be used to create queues & topics, consumers & producers.
