[#component-servlet]
= Servlet

The Servlet component of {project_name} enables basic Java Web Servlet processing and serving.

.Maven Coordinates

To include the servlet component, add a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>{groupId}</groupId>
  <artifactId>{project_key}-servlet</artifactId>
</dependency>
----

.Implicit Deployment

An application archive will be scanned for all `Servlet` implementations and added to a default deployment. 
The `@WebServlet` annotation should be used to configure the servlet as desired.

.Explicit Deployments

To have more control over the deployment, the application may use normal CDI facilities to produce instances of `DeploymentMetaData`.
Each instance of `DeploymentMetaData` will be individually deployed to the underlying servlet container.

.Management Deployments

Various other components, such as _Metrics_ and _Health_ produce additional web endpoints. 
Each of these are marked as _management_ deployments. 
By default, these management deployments will be automatically deployed alongside the application deployment.
The servlet component may be configured (see below) to separate application endpoints from management endpoints.

.Static Content

Your application may provide static resources through its classpath, under `static/`, `public/` or `META-INF/resources/` within your jar.
In a Maven-based project, that would be represented by paths such as:

* `src/main/resources/static/`
* `src/main/resources/public/`
* `src/main/resources/META-INF/resources/`

Any file in the root of those directories would be served at the root of your application's context path.
The `static` or `public` prefix is not included in the resulting URL.

For instance:

`src/main/resources/static/index.html` would be served by default at `/index.html`.

.Configuration of Primary Endpoints

If the management endpoints (see below) are not configured separately, then the primary configuration applies to all endpoints.

web.primary.host::
Sets the host or interface to bind the primary endpoint connection listener.

web.primary.port::
Sets the port to bind the primary endpoint connection listener.
If this value is set to `0`, a random available port will be used.

[#component-management-endpoints]
.Configuration of Management Endpoints

Two configuration properties control which host and port management endpoints are served from.
By default, they match the primary host and port, and serve from the same connection.

To change the management host or port, use the following configuration properties:

web.management.host::
Sets the host or interface to bind the management endpoint connection listener.

web.management.port::
Sets the port to bind the management endpoint connection listener.
If this value is set to `0`, a random available port will be used.

.Configuration of Undertow

The servlet componet includes a variety of configuration options related to the default Undertow-based implementation.

undertow.io-threads::
The number of I/O threads to use by the web server.
By default it is calculated as the maximum of `2` or the number of available CPUs.

undertow.worker-threads::
The number of worker threads used by the web server.
By default it is calculated as 8 times the number of I/O threads.

undertow.high-water::
The high water mark for a server's connections.
Once this number of connections have been accepted, accepts will be suspended for that server.

undertow.low-water::
The low water mark for a server's connections.  Once the number of active connections have dropped below this
number, accepts can be resumed for that server.

undertow.tcp-nodelay::
Configure a TCP socket to disable Nagle's algorithm.

undertow.cork::
Specify that output should be buffered.
The exact behavior of the buffering is not specified; it may flush based on buffered size or time.

.CDI Components

To enable creation of well-integrated applications, the Servlet component provides access to several CDI components.

`@Primary` `URL`::
A `URI` with the qualifier of `@Primary` is available for injection.
It specifies the URL of the primary endpoint.

`@Primary` `InetSocketAddress`::
An `InetSocketAddress` with the qualifier of `@Primary` is available for injection.
It specifies the address and port of the primary endpoint.

`@Management` `URL`::
A `URI` with the qualifier of `@Primary` is available for injection.
It specifies the URL of the management endpoint.
This may be the same as the `URL` with the `@Primary` qualifier if the management endpoint has not been separately configured.

`@Management` `InetSocketAddress`::
An `InetSocketAddress` with the qualifier of `@Primary` is available for injection.
It specifies the address and port of the management endpoint.
This may be the same as the `InetSocketAddress` with the `@Primary` qualifier if the management endpoint has not been separately configured.

[#component-servlet-metrics]
.Supported Metrics

A variety of metrics are automatically provided if xref:component-metrics[] is configured.

deployment._name_.request::
Total number of requests serviced by the named deployment.

deployment._name_.request.1xx::
Total number of requests which responded with an HTTP response code between 100 and 199.

deployment._name_.request.2xx::
Total number of requests which responded with an HTTP response code between 200 and 299.

deployment._name_.request.3xx::
Total number of requests which responded with an HTTP response code between 300 and 399.

deployment._name_.request.4xx::
Total number of requests which responded with an HTTP response code between 400 and 499.

deployment._name_.request.5xx::
Total number of requests which responded with an HTTP response code between 500 and 599.

deployment._name_.response::
Average response time for all responses.


