== Welcome to {project_name}


Greetings and welcome to {project_name}, the Java framework that combines the Eclipse Microprofile
with your favorite Java libraries for a simple yet powerful development experience. {project_name}
assumes one "application" per {project_name} instance. There is a flat classpath[NEED LINK HERE], to add a Java
library you just add it to your Maven pom.xml and you are good to go.

=== If you are coming from an Application Server background

Developing for {project_name} will be different than you are used to, primarily, there is no "Application Server"
that you deploy your application to. When you write a {project_name} application you need to add a _main method_
just like you used to do in your Java applications. On startup, {project_name} will look for this _main method_ and
execute whatever is inside that method. MORE EXPLANATION HERE

Because of the flat classpath there is no need to bundle your dependencies into a special directory of your
application or add them to a special directory in your application server. All you need to do to add a
jar from a library to your application is put it in your Maven pom.xml. This makes managing
your dependencies much easier.

=== On to our Hello World Application

Our "Hello World" application is going to use JAX-RS to serve up content at the base URL
of our application.

To get started we create a pom.xml which only really needs two elements beyond the
standard metadata.

* The {project_name} BOM[Link to Maven BOM explanation]
* If we want code completion in our editor, the dependency on {project_name}-jaxrs artifact
