[#component-opentracing]
= OpenTracing

The OpenTracing component supports the MicroProfile OpenTracing specification.

.Maven Coordinates

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>{groupId}</groupId>
  <artifactId>{project_key}-opentracing</artifactId>
</dependency>
----

.Usage

This component uses the OpenTracing `TracerResolver` to locate an appropriately-configured `Tracer` instance.
Additionally, applications may provide instances of `TracerProvider` which may also be used to discovered a fully-configured `Tracer` implementation.
The discovered `Tracer` will be registered with the `GlobalTracer` which allows for easy access in arbitrary code.

.Testing

If the OpenTracing `MockResolver` is available on the classpath (usually through a `<scope>test</scope>` dependency), it is given the highest priority for resolution.

.CDI Components

`Tracer`::
An injectable OpenTracing `Tracer`.

`TracerProvider`::
An interface which application components may implement in order to assist in resolving the current `Tracer` implementation.

.Related Information

* https://github.com/opentracing-contrib/java-tracerresolver[OpenTracing TracerResolver]

include::opentracing-jaeger.adoc[leveloffset=+1]

