[#lessons-learned]
= Lessons Learned

[quote]
Don't cling to a mistake just because you spent a lot of time making it.

.Mangling artifacts is dangerous

When you mangle and repackage a user's artifacts and dependencies, it can many times go awry.

.Don't replace Maven

Let Maven (or Gradle) handle the entirety of pulling dependencies. We cannot predict the topology of someone's repository managers, proxies and network.

.Don't get complicated with uberjars

The more complex our uberjar layout is, the harder it is to support Gradle or other non-Maven build systems.

.Classpaths are tricky

If different codepaths are required for executing from Maven, an IDE, a unit-test, and during production, you will have a *bad time*.

.Don't insist on uberjars

For Linux containers, people want layers that cleanly separate application code from runtime support code.

.Testability is important

A slow test is a test that is never willingly executed. PRs take forever to validate. Users like to be able to test their own code quickly and iteratively.

.Easily extensible means ecosystem

If it's entirely too difficult to extend the platform, the ecosystem will not grow. New integrations should be simple.

.Related: Core things should not be any more first-class than community contributions

For instance, auto-detection in WildFly Swarm only worked with core fractions; user-provided wouldn't auto-detect.

.Ensure the public-vs-private API guarantees are clear.

Intertwingly code (and javadocs) make finding the delineation between public API and private implementations difficult.

.Allow BYO components

We don't want to decide _all_ of the implementations, and certainly not versions, of random components we support.

.Be a framework, not a platform

Frameworks are easier to integrate into an existing app; a platform becomes the target with (generally too many) constraints.

.Maintain tests & documentation 

Ensure the definition of "done" includes both tests and documentation.

.Productization complexity

The greater divergence between community and product, the more effort is required for productization.
Complicating any process to automate productization from community.

.BOM complexity

Related to productization as well, but of itself having a handful of BOMs made life confusing for us and for users.
There were often times where fractions would be "Unstable" or "Experimental" for months with no real reason other than we forgot to update it.
