
[id='the-general-yaml-file-format_{context}']
= The general YAML file format

The {Thorntail} configuration item names correspond to the YAML configuration structure.
That is, if you want to write a piece of YAML configuration for some configuration property, you just need to separate the configuration property around the `.` characters.

.YAML configuration
====
For example, a configuration item documented as `thorntail.undertow.servers.KEY.default-host` translates to the following YAML structure, substituting the `KEY` segment with the `default` identifier:

[source,yaml]
----
thorntail:
  undertow:
    servers:
      default:
        default-host: <myhost>
----
====

This simple rule applies always, there are no exceptions and no additional delimiters.
Most notably, some MicroProfile specifications define configuration properties that use `/` as a delimiter, because the `.` character is used in fully qualified class names.
When writing the YAML configuration, it is still required to split around `.` and _not_ around `/`.

.YAML configuration for MicroProfile Rest Client
====
For example, MicroProfile Rest Client specifies that you can configure URL of an external service with a configuration property named `com.example.demo.client.Service/mp-rest/url`.
This translates to the following YAML:

[source,yaml]
----
com:
  example:
    demo:
      client:
        Service/mp-rest/url: http://localhost:8080/...
----
====
